{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: customer-stack-network-policy
  namespace: {{ .Values.global.customerName }}-stack
  labels:
    {{- include "customer-stack.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- range .from }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS to external services
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP to external services
    - to: []
      ports:
        - protocol: TCP
          port: 80
    # Allow internal communication
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.global.customerName }}-stack
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 11434
        - protocol: TCP
          port: 6333
        - protocol: TCP
          port: 6334
{{- end }}