{{- if .Values.aws.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customer-stack.serviceAccountName" . }}
  namespace: {{ .Values.global.customerName }}-stack
  labels:
    {{- include "customer-stack.labels" . | nindent 4 }}
  {{- with .Values.aws.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}