apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customer-environments
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: white-label-ai-assistant
spec:
  description: Project for customer environment deployments
  
  # Source repositories
  sourceRepos:
    - 'https://github.com/your-org/white-label-ai-assistant'
    - 'https://github.com/your-org/white-label-ai-assistant.git'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: '*-stack'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: 'batch'
      kind: Job
    - group: 'batch'
      kind: CronJob
    - group: 'networking.k8s.io'
      kind: NetworkPolicy
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'policy'
      kind: PodDisruptionBudget
    - group: 'autoscaling'
      kind: HorizontalPodAutoscaler
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding
  
  # Roles for project access
  roles:
    - name: admin
      description: Admin access to customer environments
      policies:
        - p, proj:customer-environments:admin, applications, *, customer-environments/*, allow
        - p, proj:customer-environments:admin, repositories, *, *, allow
        - p, proj:customer-environments:admin, clusters, *, *, allow
      groups:
        - platform-team
        - devops-team
    
    - name: developer
      description: Developer access to customer environments
      policies:
        - p, proj:customer-environments:developer, applications, get, customer-environments/*, allow
        - p, proj:customer-environments:developer, applications, sync, customer-environments/*, allow
        - p, proj:customer-environments:developer, repositories, get, *, allow
      groups:
        - development-team
    
    - name: readonly
      description: Read-only access to customer environments
      policies:
        - p, proj:customer-environments:readonly, applications, get, customer-environments/*, allow
        - p, proj:customer-environments:readonly, repositories, get, *, allow
      groups:
        - support-team
        - management-team
  
  # Sync windows for controlled deployments
  syncWindows:
    - kind: allow
      schedule: '0 9-17 * * 1-5'  # Business hours, weekdays
      duration: 8h
      applications:
        - '*'
      manualSync: true
    - kind: deny
      schedule: '0 18-8 * * *'    # Outside business hours
      duration: 14h
      applications:
        - '*'
      manualSync: false
    - kind: deny
      schedule: '0 * * * 0,6'     # Weekends
      duration: 24h
      applications:
        - '*'
      manualSync: false
  
  # Signature keys for verification
  signatureKeys:
    - keyID: platform-team-key